apiVersion: v1
kind: PersistentVolume
metadata:
 name: wp-pv
 labels:
   app: wordpress
spec:
 capacity:
  storage: 2Gi
 accessModes:
  - ReadWriteMany
 storageClassName: ""
 nfs:
  path: /nfs2
  server: 192.168.16.140

